import {
  CheckCircle,
  ArrowRight,
  ChevronLeft,
  ChevronRight,
  Command,
  File,
  FileText,
  Folder,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Server,
  Settings,
  SunMedium,
  Trash,
  User,
  Users,
  X,
  Camera,
  Edit,
  ArrowLeft,
  LogOut,
  RefreshCw,
  type LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  users: Users,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  add: Plus,
  plus: Plus,
  moreVertical: MoreVertical,
  file: File,
  folder: Folder,
  check: CheckCircle,
  fileText: FileText,
  image: Image,
  loader: Loader2,
  camera: Camera,
  edit: Edit,
  logout: LogOut,
  refresh: RefreshCw,
  server: Server,
} 