import {
  ArrowRight, 
  ArrowLeft,
  Check, 
  ChevronRight,
  ChevronsUpDown, 
  Circle, 
  Copy, 
  Edit, 
  ExternalLink, 
  File, 
  HelpCircle, 
  Home, 
  Image,
  Lightbulb,
  Loader2, 
  Mail, 
  MessageSquare, 
  Moon, 
  PanelLeft, 
  Plus, 
  PlusCircle, 
  Search, 
  Server, 
  Settings, 
  Share2, 
  Shield, 
  Sparkles,
  Sun, 
  Trash, 
  Upload,
  User, 
  Video,
  X, 
  Workflow
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  check: Check,
  chevronDown: ChevronsUpDown,
  chevronRight: ChevronRight,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  helpCircle: HelpCircle,
  home: Home,
  image: Image,
  lightbulb: Lightbulb,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  sparkles: Sparkles,
  spinner: Loader2,
  trash: Trash,
  upload: Upload,
  user: User,
  video: Video,
  panelLeft: PanelLeft
};

export {Icons};
